clone:
  git:
    image: plugins/git
    recursive: true
    clone_mode: oauth
    skip_verify: true

pipeline:
  compile:
      image: plugins/docker
      repo: registry.contraslash.com:5000/contraslash/tpaga
      secrets: [ docker_username, docker_password ]
      registry: registry.contraslash.com:5000
      tags: [latest]

  deploy:
    image: appleboy/drone-ssh
    username: root
    secrets: [ ssh_key, docker_username, docker_password, DATABASE_DATABASE, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST, AWS_STORAGE_BUCKET_NAME, AWS_ACCESS_KEY_ID, AWS_STORAGE_BUCKET_NAME, AWS_MEDIA_S3_REGION_NAME, ENV, DEBUG, TPAGA_USERNAME, TPAGA_PASSWORD]
    envs: [docker_username, docker_password, DATABASE_DATABASE, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST, AWS_STORAGE_BUCKET_NAME, AWS_ACCESS_KEY_ID, AWS_STORAGE_BUCKET_NAME, AWS_MEDIA_S3_REGION_NAME, ENV, DEBUG, TPAGA_USERNAME, TPAGA_PASSWORD]
    host: tpaga.contraslash.com
    port: 22
    script:
      - echo "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.contraslash.com:5000"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.contraslash.com:5000
      - docker pull registry.contraslash.com:5000/contraslash/tpaga
      - docker service rm tpaga
      - echo docker service create --name tpaga --label traefik.port=8000 --label "traefik.frontend.rule=Host:tpaga.contraslash.com" --network traefik-network  --env DATABASE_DATABASE=$DATABASE_DATABASE --env  DATABASE_USERNAME=$DATABASE_USERNAME --env  DATABASE_PASSWORD=$DATABASE_PASSWORD --env  DATABASE_HOST=$DATABASE_HOST --env  AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME --env  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --env  AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME --env  AWS_MEDIA_S3_REGION_NAME=$AWS_MEDIA_S3_REGION_NAME --env  ENV=$ENV --env  DEBUG=$DEBUG --env  TPAGA_USERNAME=$TPAGA_USERNAME --env  TPAGA_PASSWORD=$TPAGA_PASSWORD  registry.contraslash.com:5000/contraslash/tpaga
      - docker service create --name tpaga --label traefik.port=8000 --label "traefik.frontend.rule=Host:tpaga.contraslash.com" --network traefik-network --env DATABASE_DATABASE=$DATABASE_DATABASE --env  DATABASE_USERNAME=$DATABASE_USERNAME --env  DATABASE_PASSWORD=$DATABASE_PASSWORD --env  DATABASE_HOST=$DATABASE_HOST --env  AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME --env  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --env  AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME --env  AWS_MEDIA_S3_REGION_NAME=$AWS_MEDIA_S3_REGION_NAME --env  ENV=$ENV --env  DEBUG=$DEBUG --env  TPAGA_USERNAME=$TPAGA_USERNAME --env  TPAGA_PASSWORD=$TPAGA_PASSWORD  registry.contraslash.com:5000/contraslash/tpaga


  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: devops
    when:
     status: [ success, failure ]
