from django.utils.translation import ugettext_lazy as  _

from base import conf


ITEM_PREFIX = "ITEM"


ITEM_LIST_URL_NAME = ITEM_PREFIX + conf.LIST_SUFFIX
ITEM_CREATE_URL_NAME = ITEM_PREFIX + conf.CREATE_SUFFIX
ITEM_DETAIL_URL_NAME = ITEM_PREFIX + conf.DETAIL_SUFFIX
ITEM_UPDATE_URL_NAME = ITEM_PREFIX + conf.UPDATE_SUFFIX
ITEM_DELETE_URL_NAME = ITEM_PREFIX + conf.DELETE_SUFFIX

ORDER_PREFIX = "ORDER"


ORDER_LIST_URL_NAME = ORDER_PREFIX + conf.LIST_SUFFIX
ORDER_CREATE_URL_NAME = ORDER_PREFIX + conf.CREATE_SUFFIX
ORDER_DETAIL_URL_NAME = ORDER_PREFIX + conf.DETAIL_SUFFIX
ORDER_UPDATE_URL_NAME = ORDER_PREFIX + conf.UPDATE_SUFFIX
ORDER_DELETE_URL_NAME = ORDER_PREFIX + conf.DELETE_SUFFIX
ORDER_CHECKOUT_URL_NAME = ORDER_PREFIX + "_checkout"
ORDER_CONFIRM_URL_NAME = ORDER_PREFIX + "_confirm"
ORDER_REFUND_URL_NAME = ORDER_PREFIX + "_refund"


ORDER_DELIVERED = "delivered"
ORDER_CANT_BE_REFUND = _("Order can't be refund")

ORDERITEM_PREFIX = "ORDERITEM"


ORDERITEM_LIST_URL_NAME = ORDERITEM_PREFIX + conf.LIST_SUFFIX
ORDERITEM_CREATE_URL_NAME = ORDERITEM_PREFIX + conf.CREATE_SUFFIX
ORDERITEM_DETAIL_URL_NAME = ORDERITEM_PREFIX + conf.DETAIL_SUFFIX
ORDERITEM_UPDATE_URL_NAME = ORDERITEM_PREFIX + conf.UPDATE_SUFFIX
ORDERITEM_DELETE_URL_NAME = ORDERITEM_PREFIX + conf.DELETE_SUFFIX


MAIN_PREFIX = "MAIN"

MAIN_INDEX = "index"

MAIN_INPUT_LABEL = _("Item")
MAIN_QUANTITY_LABEL = _("Quantity")

PERMISSIONS = {
    'manage_orders': {
        'app_label': 'simple_ecommerce',
        'model': 'order',
        'codename': 'manage_order',
    }
}

GROUPS = {
    'operator': {
        "name": _("Operator"),
        'permissions': [
            "manage_orders",
        ]
    },
}
