# Generated by Django 2.1.3 on 2018-11-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ecommerce', '0003_auto_20181118_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.TextField(default=''),
        ),
    ]
